[package]
name = "Stisty"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
doc = "0.0.0"
log = "0.4.22"
log4rs = "1.3.0"
ratatui = "0.28.2-alpha.5"
crossterm = "0.28.1"
anyhow = "1.0.89"
thiserror = "1.0.64"