[package]
name = "Stisty"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
csv = "*"
log = "*"
log4rs = "*"
ratatui = "*"
crossterm = "*"
anyhow = "*"
charming = { version = "*", features = ["html"] }
clap = { version = "*", features = ["derive", "cargo"] }
clap_complete = "*"
inquire = "*"
fuzzy-matcher = "*"
